server:
  servlet:
    context-path: /example
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC
    username: root
    password: xiao
